CREATE DATABASE CONSULTORIODB
GO
USE CONSULTORIODB

CREATE TABLE PERMISOS (
	id INT IDENTITY PRIMARY KEY,
	permiso_name VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE ROLES (
	id INT IDENTITY PRIMARY KEY,
	rol_name VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE PERMISOS_X_ROLES (
	id INT IDENTITY,
	id_rol INT NOT NULL,
	id_permiso INT NOT NULL,
	FOREIGN KEY (id_rol) REFERENCES ROLES(id),
	FOREIGN KEY (id_permiso) REFERENCES PERMISOS(id),
	PRIMARY KEY (id, id_rol, id_permiso)
)

CREATE TABLE USUARIOS (
	id INT IDENTITY PRIMARY KEY,
	email VARCHAR(70) NOT NULL UNIQUE,
	password_hash VARCHAR(200),
	img_url VARCHAR(200),
	id_rol INT FOREIGN KEY REFERENCES ROLES(id),
	fecha_creacion DATETIME NULL
)

CREATE TABLE RECEPCIONISTAS (
	id INT IDENTITY PRIMARY KEY,
	usuario_id INT NULL UNIQUE,
	nombre VARCHAR(50) NOT NULL,
	apellido VARCHAR(50) NOT NULL,
	nacimiento DATE NOT NULL
	FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id)
)

CREATE TABLE ESPECIALISTAS (
	id INT IDENTITY PRIMARY KEY,
	usuario_id INT NULL UNIQUE,
	nombre VARCHAR(50) NOT NULL,
	apellido VARCHAR(50) NOT NULL,
	nacimiento DATE NOT NULL,
	FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id)
)

CREATE TABLE ESPECIALIDADES (
	id INT IDENTITY PRIMARY KEY,
	especialidad_name VARCHAR(50) NOT NULL UNIQUE,
)

CREATE TABLE ESPECIALIDADES_X_ESPECIALISTAS (
	id INT IDENTITY,
	especialista_id INT NOT NULL,
	especialidad_id INT NOT NULL,
	FOREIGN KEY (especialista_id) REFERENCES ESPECIALISTAS(id),
	FOREIGN KEY (especialidad_id) REFERENCES ESPECIALIDADES(id),
	PRIMARY KEY (id, especialista_id, especialidad_id)
)

CREATE TABLE DIAS (
	id INT IDENTITY PRIMARY KEY,
	nombre VARCHAR(16) NOT NULL,
)

CREATE TABLE TURNOS_DE_TRABAJO (
	especialista_id INT NOT NULL,
	dia_id INT NOT NULL,
	hora_inicio TIME NOT NULL,
	hora_final TIME NOT NULL,
	FOREIGN KEY (especialista_id) REFERENCES ESPECIALISTAS (id),
	FOREIGN KEY (dia_id) REFERENCES DIAS(id),
	PRIMARY KEY (especialista_id, dia_id, hora_inicio, hora_final)
)

CREATE TABLE PACIENTES (
	id INT IDENTITY PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL,
	apellido VARCHAR(50) NOT NULL,
	email VARCHAR(70) NOT NULL UNIQUE,
	telefono VARCHAR(20) NOT NULL UNIQUE,
	nacimiento DATE NOT NULL,
	dni VARCHAR(15) NOT NULL UNIQUE
)

CREATE TABLE ESTADOS (
	id INT IDENTITY PRIMARY KEY,
	tipo VARCHAR(50)
)
CREATE TABLE TURNOS (
	id INT IDENTITY PRIMARY KEY,
	paciente_id INT NOT NULL,
	especialista_id INT NOT NULL,
	fecha DATE NOT NULL,
	hora TIME NOT NULL,
	estado_id INT NOT NULL,
	observacion TEXT,
	FOREIGN KEY (paciente_id) REFERENCES PACIENTES(id),
	FOREIGN KEY (especialista_id) REFERENCES ESPECIALISTAS(id),
	FOREIGN KEY (estado_id) REFERENCES ESTADOS(id),
	UNIQUE (paciente_id, fecha, hora),
	UNIQUE (especialista_id, fecha, hora)
)
